seed: 42
paths:
  data_root: /home/florianr/MG_Farm/0_Data/MGFarm_18650_FE
  out_root: /home/florianr/MG_Farm/1_Scripts/DL_Models/LFP_SOC_SOH_Model/1_training/1.7.1.0/outputs
  model_out_root: /home/florianr/MG_Farm/1_Scripts/DL_Models/LFP_SOC_SOH_Model/2_models/SOC_1.7.1.0
model:
  type: GRU_MLP
  features:
  - Voltage[V]
  - Current[A]
  - "Temperature[\xB0C]"
  - SOH
  - Q_c
  - dU_dt[V/s]
  - dI_dt[A/s]
  - dt_s
  hidden_size: 140
  mlp_hidden: 150
  num_layers: 1
  dropout: 0.08
augmentation:
  time_warp_prob: 0.85
  dt_jitter_std_s: 0.01
  dt_jitter_clip_s: 0.05
  min_dt_s: 0.9
  max_dt_s: 1.1
  current_channel_dropout_prob: 0.25
training:
  seq_chunk_size: 2024
  lr: 0.00012
  weight_decay: 1.0e-05
  max_grad_norm: 1.0
  epochs: 64
  val_interval: 2
  early_stopping: 12
  batch_size: 192
  accum_steps: 1
  window_stride: 1
  compile: false
  scheduler:
    type: cosine_warm_restarts
    T_0: 150
    eta_min_factor: 0.05
  train_window_stride: 8
  val_window_stride: 32
  save_every_n: 0
cells:
  train:
  - MGFarm_18650_C01
  - MGFarm_18650_C03
  - MGFarm_18650_C05
  - MGFarm_18650_C11
  - MGFarm_18650_C17
  - MGFarm_18650_C23
  val:
  - MGFarm_18650_C07
  - MGFarm_18650_C19
  - MGFarm_18650_C21
export:
  save_best_only: true
  save_every_n: 0
  to_onnx: true
  onnx_opset: 17
  stateful_onnx: true
tracking:
  csv_log: true
  csv_file: /home/florianr/MG_Farm/1_Scripts/DL_Models/LFP_SOC_SOH_Model/1_training/1.7.1.0/outputs/training_log.csv
  tensorboard: false
dataloader:
  num_workers: 12
  prefetch_factor: 6
  persistent_workers: true
  pin_memory: true
  scaler_fit_stride: 8
  scaler_fit_max_rows_per_cell: 750000
